# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: 2025 Erlang Ecosystem Foundation

on:
  workflow_call: {}

name: "Smoke Test"

permissions:
  contents: read

jobs:
  mix:
    name: "Mix Task"

    runs-on: ubuntu-latest

    env:
      MIX_ENV: prod

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          submodules: true

      - uses: ./.github/actions/setup-runtime-env
        with:
          mix-env: prod

      - name: "Test All Combinations"
        uses: ./.github/actions/validate-cyclonedx-bom
        with:
          command: "mix sbom.cyclonedx"
          test-name: "Mix"

  burrito:
    name: "Burrito Binary"

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          submodules: true

      - name: "Download Burrito Binary"
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v5.0.0
        with:
          name: binary
          path: ./burrito_artifacts

      - name: "Make Binary Executable"
        run: |
          chmod +x ./burrito_artifacts/mix_sbom_Linux_X64

      - name: "Test All Combinations"
        uses: ./.github/actions/validate-cyclonedx-bom
        with:
          command: "./burrito_artifacts/mix_sbom_Linux_X64 cyclonedx"
          command-args: "."
          test-name: "Burrito"

  escript:
    name: "EScript"

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          submodules: true

      - uses: ./.github/actions/setup-runtime-env

      - name: "Download EScript"
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v5.0.0
        with:
          name: escript
          path: ./escript_artifacts

      - name: "Make EScript Executable"
        run: |
          chmod +x ./escript_artifacts/mix_sbom

      - name: "Test All Combinations"
        uses: ./.github/actions/validate-cyclonedx-bom
        with:
          command: "./escript_artifacts/mix_sbom cyclonedx"
          command-args: "."
          test-name: "EScript"