# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: 2025 Erlang Ecosystem Foundation

on:
  workflow_call: {}

name: "Smoke Test"

permissions:
  contents: read

jobs:
  mix:
    name: "Mix Task"

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-runtime-env
        with:
          mix-env: prod

      - name: "Test All Combinations"
        uses: ./.github/actions/validate-cyclonedx-bom
        with:
          command: "mix sbom.cyclonedx"
          test-name: "Mix"

  burrito:
    name: "Burrito Binary"

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Download Burrito Binary"
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v5.0.0
        with:
          name: binary
          path: ./burrito_artifacts

      - name: "Make Binary Executable"
        run: |
          chmod +x ./burrito_artifacts/mix_sbom_Linux_X64

      - name: "Test All Combinations"
        uses: ./.github/actions/validate-cyclonedx-bom
        with:
          command: "./burrito_artifacts/mix_sbom_Linux_X64 cyclonedx"
          command-args: "."
          test-name: "Burrito"

  escript:
    name: "EScript"

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-runtime-env

      - name: "Download EScript"
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v5.0.0
        with:
          name: escript
          path: ./escript_artifacts

      - name: "Make EScript Executable"
        run: |
          chmod +x ./escript_artifacts/mix_sbom

      - name: "Test All Combinations"
        uses: ./.github/actions/validate-cyclonedx-bom
        with:
          command: "./escript_artifacts/mix_sbom cyclonedx"
          command-args: "."
          test-name: "EScript"